# Generated by Django 4.1 on 2022-10-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Roles',
            new_name='User_Role',
        ),
    ]
