# Generated by Django 4.1 on 2022-11-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_administrator_user_id_alter_user_user_role'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompany',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_companies', to='flights.country'),
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_companies', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airlinecompany'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_as_destination', to='flights.country'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_as_origin', to='flights.country'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flight'),
        ),
    ]
