# Generated by Django 4.1 on 2022-11-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0002_alter_airlinecompany_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompany',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
