# Generated by Django 4.1 on 2022-11-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role_role_name_user_and_more'),
        ('flights', '0003_alter_airlinecompany_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompany',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_companies', to='accounts.user'),
        ),
    ]
